### ISSUE TITLE
Bug when using regex

### ISSUE THREAD

**Issue by dreampulse** [Olical/EventEmitter#100]
```
$ node
> var EventEmitter = require('wolfy87-eventemitter')
undefined
> var ee = new EventEmitter();
undefined
> ee.on(/change/, () => console.log('ok!'));
EventEmitter { _events: {} }
> ee.emit('change');
EventEmitter { _events: { change: [] } }
```
At this point I expect a `ok!` console.log

Without regex it will work
```
> ee.on('change', () => console.log('hmm!'));
EventEmitter { _events: { change: [ [Object] ] } }
> ee.emit('change');
hmm!
EventEmitter { _events: { change: [ [Object] ] } }
>
```

**Comment by dreampulse** [comment]
it seems to work if I predefine the eventName.
`ee.defineEvent('change')`
But this should not be required. So it's still a bug!

**Comment by Olical** [comment]
Hey, I apologise for the confusion! This is a limitation of how I implemented regular expressions. I wanted to add some support without bloating the library, [it's mentioned in the guide](https://github.com/Olical/EventEmitter/blob/master/docs/guide.md#using-regular-expressions) and possibly the API documentation too.

You *must* define the events first if you wish to use regular expressions on them I'm afraid. There's an example of regex use in [this fiddle](http://jsfiddle.net/Wolfy87/JqRvS/).
