### ISSUE TITLE
Tests fails under IE <= 8

### ISSUE THREAD

**Issue by garex** [Olical/EventEmitter#104]
chai is undefined

**Comment by garex** [comment]
Also under Chrome 6

**Comment by garex** [comment]
Also under FF 2, 3.5, 3.6.

Under FF >=4 is ok.

**Comment by garex** [comment]
Also under Opera 8, 10.10, 11.50

Opera >= 11.60 is ok

**Comment by garex** [comment]
Also under safari 3.1.2

Safari >= 4 is ok

**Comment by Olical** [comment]
From the [Chai installation page](http://chaijs.com/guide/installation/).

> Currently supports all modern browsers: IE 9+, Chrome 7+, FireFox 4+, Safari 5+. Please note that the should style is currently not compatible with IE9.

So chai just doesn't support old browsers, I'm not really sure what I can do about this other than replacing the entire assertion library.

**Comment by garex** [comment]
@Olical I think it will be best. As the mission stated is "Evented JavaScript for the **browser**"

Currently I decided to use https://github.com/mkuklis/asEvented as it uses simple good old qunit, that just works and I'm just sure that it will work on all ancient browsers.

For quick tests I used this service: https://crossbrowsertesting.com

Just contact them and request opensource-project access.

**Comment by Olical** [comment]
Thanks for pointing this out, I will keep it in mind if I develop this project further. `asEvented` looks fine too :)
