### ISSUE TITLE
onListenerAdded / onListenerRemoved events ?

### ISSUE THREAD

**Issue by vitalets** [Olical/EventEmitter#105]
hi, I need to catch events when listener added / removed. 
Is it possible or planned? (as I don't see it in docs)
thanks

**Comment by Olical** [comment]
Hi there. This isn't planned I'm afraid. I would add this by extending the emitter class and adding hooks there. Will that solve your issue?

**Comment by vitalets** [comment]
yes. But currently we moved to our own solution, so if there are no other reasons to do that, don't do that :)
btw, we used `onFirstListenerAdded / onLastListenerRemoved` events to manage dependent subscriptions.

**Comment by Olical** [comment]
Excellent, glad you found a solution! :)
