### ISSUE TITLE
unable to browserify + babelify v5

### ISSUE THREAD

**Issue by jedierikb** [Olical/EventEmitter#109]
Attempts to browserify and babelify v5 fail while v4.2.0 succeeds.
Somehow `.call(this)` is converted to `.call(undefined)`

issue ticket which brought me here:
https://github.com/metafizzy/isotope/issues/976#issuecomment-218467528

**Comment by Olical** [comment]
The only difference is that it was changed from `this` to `exports` [between v4.2.0 and v4.3.0](https://github.com/Olical/EventEmitter/compare/v4.2.0...v4.3.0). Was probably one of these two commits.

 * 2aae323885
 * 100d1d2cb4

**Comment by jedierikb** [comment]
I tested both of these specific commits and both failed to work when browserified and babelified.

**Comment by Olical** [comment]
What about a commit before both of those? Like this c47ab927de3a

**Comment by jedierikb** [comment]
That works.

**Comment by Olical** [comment]
Very interesting, thank you very much for reporting and testing!

**Comment by Olical** [comment]
I just tried this through browserify and it worked fine, are you sure it's not because of how you're importing it?
