### ISSUE TITLE
Small copy/paste based typo in API docs

### ISSUE THREAD

**Issue by redders6600** [Olical/EventEmitter#114]
The documentation for `addListeners` and `removeListeners` reads:

> If you pass an object as the second argument you can add to multiple events at once. 

Actually for these functions it's the first argument that can be an object.

**Comment by Olical** [comment]
I've fixed the documentation, does my pull request look good to you?

**Comment by redders6600** [comment]
It does - next time I'll make one myself, sorry ;)

**Comment by Olical** [comment]
No problem! Thanks for flagging it up, I had to lock down the `devDependencies` too, remembering versions from years ago is probably something only I could have done there. I don't know why past me thought using `*` was a good idea, but it meant the documentation generator no longer worked with the latest one.
