### ISSUE TITLE
off -> removeEvent when passed only one argument

### ISSUE THREAD

**Issue by Kasheftin** [Olical/EventEmitter#117]
That's not an issue really, just a though. 
What if calling off with only one argument (the event name) will call removeAllListeners method instead of   removeListener?

**Comment by Kasheftin** [comment]
I mean `off` word is very popular, jquery uses it for unsubscribing from events. And there (in jquery code) the second argument is optional. So it may confuse that eventEmitter.off("someEvent") does not work at all, and one has to use removeEvent instead.

**Comment by Olical** [comment]
I'd rather not go down this path. I don't like having aliases as it is, and if someone passes a null reference to `off` by accident it'll remove everything. This could cause issues for people down the line. Thanks for the suggestion, but I'll leave it as it is for now.
