### ISSUE TITLE
Module '"wolfy87-eventemitter"' has no default export

### ISSUE THREAD

**Issue by bennyn** [Olical/EventEmitter#121]
I wanted to use `EventEmitter` in TypeScript, doing this:

```typescript
import EventEmitter from "wolfy87-eventemitter";
```

But all I get is:

> error TS1192: Module '"wolfy87-eventemitter"' has no default export.

I am using these typings from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped):

```typescript
"wolfy87-eventemitter": "registry:dt/wolfy87-eventemitter#4.2.9+20160913103710"
```

Can you help me getting it to work?

**Comment by Olical** [comment]
Some curly braces should work.

```js
import {EventEmitter} from "wolfy87-eventemitter";
```

I've never used TypeScript though so ¯\\\_(ツ)\_/¯

**Comment by bennyn** [comment]
```typescript
import {EventEmitter} from "wolfy87-eventemitter";
```

leads to:

> error TS2305: Module '"wolfy87-eventemitter"' has no exported member 'EventEmitter'

I will have a look what's the issue... I installed your module via:

```bash
npm install --save @types/wolfy87-eventemitter
```

**Comment by bennyn** [comment]
Found the solution:

```typescript
import * as EventEmitter from "wolfy87-eventemitter";
```

😃

**Comment by Olical** [comment]
Cool! I will forever be perplexed by the JavaScript module system.

**Comment by bennyn** [comment]
You are not alone: https://hackernoon.com/how-it-feels-to-learn-javascript-in-2016-d3a717dd577f 😀

**Comment by bandersen22000** [comment]
You can also use:
`import EventEmitter from 'wolfy87-eventemitter';`
