### ISSUE TITLE
addListener validation

### ISSUE THREAD

**Issue by jbrekelmans** [Olical/EventEmitter#122]
The validation seems to allow the following "listener" to be added, but I imagine this causes an error when emitting the event?
o.addListener('event1', { listener: { listener: () => Console.log('o.event1') } })

**Comment by Olical** [comment]
I suppose it would. `isValidListener` will recursively walk this object until it gets to the function, then it returns true.

Then when emit goes to execute this object it will throw an error. Good catch. Not sure what should be done about it though, is it really worth fixing? Has this broken something for you? Good catch though.

**Comment by jbrekelmans** [comment]
Well the fix would be fairly easy, but it doesn't break anything for me (and I think for no one else either). Came across it when looking at the code.

**Comment by Olical** [comment]
Going to close this for now then since it's not harming anyone but will bear it in mind. I'm trying to keep work on this to a minimum since it's in a fairly good place.
