### ISSUE TITLE
changelog or history?

### ISSUE THREAD

**Issue by Pomax** [Olical/EventEmitter#126]
Is there a changelog for the major versions and how they change things up? We're doing some npm maintenance and one of the changes is bumping wolfy87-eventemitter from v4.3 to v5.1, but it's not clear whether semver is being followed (e.g. 5 is API-incompatible with 4) or whether it's a rewrite that maintains the same API.

**Comment by Olical** [comment]
I'm afraid I started this project at the start of my career and have carried it all the way through so far. I didn't know the connotations of semver or the importance of change logs at the time, so I'm afraid there's nothing.

BUT, I can offer some advice and reassurance. When upgrading any library, even if you _think_ they follow semver to the letter, you should write some tests in your suite around that library. This is a great way to _learn_ a library as well as protect yourself against change. You may even end up fixing something upstream. I know it's extra work, but some people think TDD or even tests are extra work, they offer the same reward. A stable system over time.

The reassurance is that I have deliberately kept the surface API the same. I bumped the major version when I rewrote it, but kept the method signatures the same. I can't see you having any issues, but you could always check the docs from the old version (use git tags) and compare them to your desired version.

If you only use add and remove event listener, you only need to check how they work (or test them!).

I know it's not idea, but I hope this helps a little, it's all I can offer really. I have learnt from this on projects like [react-faux-dom](https://github.com/Olical/react-faux-dom/blob/master/CHANGES.md), but I didn't learn that in time for EventEmitter.

Semver is great and all, but you can't put absolute trust in it, you need some tools in your brain to deal with changing dependencies and being sure that they work in your new system. Tests are the best way, in my opinion.

(sorry that this turned into a sort of blog post, I didn't want to just say "no changelog sorry", I wanted to offer _some_ sort of help too)

**Comment by Pomax** [comment]
Totally understandable - thanks for the amazing answer!
