### ISSUE TITLE
Type Definitions

### ISSUE THREAD

**Issue by matthiasg** [Olical/EventEmitter#131]
When I install this module using `yarn` it correctly downloads all files, but using it with Typescript fails with the compiler complaining about the d.ts file not declaring a module.

When I install the package with `npm` the unpacked folder in node_modules doesn't contain the d.ts file at all and typescript works fine.

A) Should the d.ts file not export/declare a module ?
B) Why is the d.ts file not included in the package npm installs but is in yarn ?

**Comment by Olical** [comment]
I'm afraid I have no idea about the first part. I have never touched TypeScript and I do not wish to. I merged the PR that added this definition file this morning under the impression that it couldn't cause any harm. https://github.com/Olical/EventEmitter/pull/130

With regards to your second question, maybe there's a npmignore or list of files that are allowed in the package somewhere. Probably in the package.json. I'm guessing that should be easy to fix.

**Comment by Olical** [comment]
The ts file is there when I install the package through npm.

**Comment by jdanford** [comment]
@matthiasg I'm the one that added the `.d.ts` file, something I don't have much experience with, so I apologize for not knowing more about the interactions between TypeScript and npm. I can make the structure match the [DefinitelyTyped version](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec620daccfa0ad167ba046651fb5fef69e8a/types/wolfy87-eventemitter/index.d.ts), as that seems to work.

**Comment by jdanford** [comment]
@matthiasg I (hopefully) fixed it on my fork, can you try reinstalling it with npm from `git://github.com/jdanford/EventEmitter.git#363023e5b14b05cbd5a67e13cd8d55bcc0ea6906`?

**Comment by landonpoch** [comment]
I'm also seeing an issue when trying to import into a typescript project.  File is not a module.

**Comment by matthiasg** [comment]
The first part of the question is not related directly to typescript. Npm just doesn't unpack the tgz correctly. The d.ts file is just missing after installing. This has the coincidental benefit of allowing ts to compile , but it should not have happened. 

I will try again today.

**Comment by landonpoch** [comment]
@matthiasg - I'm getting the d.ts file after installing.  In my case, I'm pretty sure the error I'm seeing is based on the fact that it exports nothing as stated above.

Also, the package.json now specifies a types entry point.  I'm sure you already know this but if you aren't getting the d.ts file for whatever reason, and the types property is specified, I'm guessing that would probably create issues.

**Comment by jdanford** [comment]
Again, I want to apologize for screwing this up. I'm one of those weird people that avoid JavaScript package managers, so I didn't realize that different module systems would affect how exports work. @landonpoch have you tried installing this package from the commit I posted?

**Comment by landonpoch** [comment]
@jdanford Yeah, that link you provided appears to fix the issue for me.  In the meantime, I'm going to lock down to 5.1.x instead of 5.x.x.  When the fix gets merged in and published then I'll accept the upgrade.

**Comment by jdanford** [comment]
Alright, if that seems to work then I'll go ahead and make a PR for the fix!

**Comment by matthiasg** [comment]
@landonpoch are you using npm v 5?

**Comment by Olical** [comment]
Try `wolfy87-eventemitter@5.2.1`. Thanks @jdanford :smile:

**Comment by landonpoch** [comment]
@matthiasg yes I'm using npm v5.
