### ISSUE TITLE
Typings not working on TypeScript 2.3

### ISSUE THREAD

**Issue by lifenautjoe** [Olical/EventEmitter#138]
Hello, 

I believe the typings for the project are no longer working in TypeScript 2.x.

My stack is TypeScript@**2.3.3**, Node@**8.1.2** and npm@**5.0.3** .

Importing it with
```ts
import EventEmitter = require('wolfy87-eventemitter');
```
Results in
```sh
Import assignment cannot be used when targeting ECMAScript 2015 modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.
```

Importing it with 
```ts
import * as EventEmitter from 'wolfy87-eventemitter';
```
Results in 
```sh
EventEmitter" resolves to a non-module entity and cannot be imported using this construct.
```

Importing it with 
```ts
import {EventEmitter} from 'wolfy87-eventemitter';
```
Results in 
```sh
EventEmitter" resolves to a non-module entity and cannot be imported using this construct.
```

And finally, importing it with
```ts
import EventEmitter from 'wolfy87-eventemitter';

```
Results in 
```sh
/EventEmitter"' has no default export.
```

Setting the `tsconfig.json` module format to `"commonjs"` does not fix the issue as well.

**Comment by lifenautjoe** [comment]
The [declaration files](https://github.com/primus/eventemitter3/blob/master/index.d.ts) from [eventemitter3](https://github.com/primus/eventemitter3) work flawlessly with an

```ts
import {EventEmitter} from 'eventemitter'
```

Their API is the same so perhaps copying them is an idea?

**Comment by Olical** [comment]
Oh, that's bad. I don't use TypeScript and I don't intend to. Does this work for you? https://www.npmjs.com/package/@types/wolfy87-eventemitter

Maybe I can just delete the definitions from this repo and let people rely on those. I'd rather delete the types in this repository since I don't understand the syntax.

**Comment by lifenautjoe** [comment]
Hey Olical,

There's a pretty big typescript community now so I would recommend making your library to work out-of-the-box :) . I have updated the type definitions and opened PR #139 . These are the definitions of eventemitter3 as I mentioned previously and work perfectly.

Cheers.

**Comment by Olical** [comment]
Yep, I realise that there is a rather large community, I don't trust myself to write support for them though, I'd rather someone that knows what they're doing did that 😄

I don't even write JavaScript anymore, hah.

So, does this new definition file work for you if you install it locally? I thought the APIs differed slightly...

**Comment by lifenautjoe** [comment]
It does change a little bit, I'll add the remaining interfaces in the weekend.

**Comment by Olical** [comment]
@lifenautjoe Hero 🎉

Obviously no pressure, I just don't trust myself to make these changes. Someone who actually knows TypeScript will be so much better at this 😄

**Comment by Olical** [comment]
I think this PR is the best of both worlds. It has your fixes for the package structure as well as the original method typing. Does it work for you, @lifenautjoe? :) https://github.com/Olical/EventEmitter/pull/140

**Comment by Olical** [comment]
Fixed with https://github.com/Olical/EventEmitter/pull/140

**Comment by lifenautjoe** [comment]
Hey man! Sorry, I did checked it out but forgot to report back. It works! 

Thanks for the fix.

**Comment by Olical** [comment]
No problem! Glad it works now 😄
