### ISSUE TITLE
How to pass args with emit call?

### ISSUE THREAD

**Issue by nickmetal** [Olical/EventEmitter#143]
What I expect 
`emitter.emit('fooEvent', {someKey: 123});`

... and my fooEvent handler will receive this data object in its args.

**Comment by Olical** [comment]
Yep, that's how it works. Are you having an issue then?

**Comment by nickmetal** [comment]
I tried with this example ...

```
var EventEmitter = require('wolfy87-eventemitter');
var ee = new EventEmitter();

function listener(data) {
    console.log('The foo event has been emitted with args: ', data);
}


ee.once('foo', listener);
ee.emitEvent('foo', {someKey: 123});
```
and my console.log was `The foo event has been emitted with args: , undefined`

I just replaced `ee.emitEvent` with `ee.emit('foo', {someKey: 123})` and all works good, sorry :)
