### ISSUE TITLE
Method signature with wrong type

### ISSUE THREAD

**Issue by alexburlton** [Olical/EventEmitter#148]
https://github.com/Olical/EventEmitter/blob/1e2c824c0ddce1e73a6b2a8c0ebc912a08a811d6/EventEmitter.d.ts#L435

The signature of this method is incorrect - in the actual JS implementation 'args' is treated as an array element (not varargs). So, for a listener that accepts a single argument, you actually need to type `emitEvent('MyEvent', [foo])` rather than `emitEvent('MyEvent', foo)` as the TS signature suggests.

**Comment by Olical** [comment]
Ah, I didn't add the ts file and I've never used ts. Any chance that someone that knows what they're doing could update this and I'll merge it? If not I'll have a look eventually. Does the `...` just need removing?

**Comment by alexburlton** [comment]
Yeah I can probably look at it today at some point
