### ISSUE TITLE
addListener add even if already exist

### ISSUE THREAD

**Issue by SimplyLab** [Olical/EventEmitter#151]
I don't understand why the code don't detect I have already add the same Listener for a specific string.

The "indexOfListener" function try to compare if listener already exist by comparing the function.

    function indexOfListener(listeners, listener) {
        var i = listeners.length;
        while (i--) {
            if (listeners[i].listener === listener) {
                return i;
            }
        }

        return -1;
    }

I must add .toString() to the listeners to be able to compare them.

" if (listeners[i].listener.toString()  === listener.toString()) {

My test listeners are as simple as : function() { alert('test'); }

listeners[i].listener return apparently the string in the console.log, and listener too.
But === only work using toString()....

Can you understand what I do badly ? I test on the latest chrome.

**Comment by Olical** [comment]
I'm not sure what the problem is here I'm afraid. Adding two listeners
under the same event name is perfectly valid, or is that not the issue? I
may be misunderstanding.

**Comment by SimplyLab** [comment]
Thanks. My question was not clear.

If I look at the API documentation we can see that :

-------------------------------
addListener
Adds a listener function to the specified event.
The listener will not be added if it is a duplicate.  <==== That is the problem
If the listener returns true then it will be removed after it is called.
If you pass a regular expression as the event name then the listener will be added to all events that match it.

param (String | RegExp) evt - Name of the event to attach the listener to.
param (Function) listener - Method to be called when the event is emitted. If the function returns true then it will be removed after calling.
return (Object) - Current instance of EventEmitter for chaining.
-------------------------------

We can see that "The listener will not be added if it is a duplicate. "

So calling at 2 differents place, for example ee.addListener( 'myEvent', function() { alert('Hi');} ) will not drive to have 2 duplicates trigger for "myEvent".

Looking at the source code, i found the function indexOfListener(listeners, listener) who try to find in the listerners array, if a function is already "registered". If yes, it will not create a new listener.

But, the indexOfListener(listeners, listener) work only if I add "toString()" after my functions. If not, it consider that function() { alert('Hi'); and function() { alert('Hi'); are not the same.

**Comment by Olical** [comment]
Yes, this is because these are not the same:

```js
// This is false.
function () { return 1 } === function () { return 1 }

const f = function () { return 1 }

// This is true.
f === f
```

If you're creating functions through the literal syntax and not reusing the reference to them each function will be a _different_ function. It may do the same thing, but it's a new function instance. If you want to reuse the same reference, store it in a `var/let/const` as shown above.

**Comment by SimplyLab** [comment]
Ho, ok ! It's perfectly clear.

Thank you !

**Comment by Olical** [comment]
No problem! 😊
