### ISSUE TITLE
Extending Classes

### ISSUE THREAD

**Issue by juuxstar** [Olical/EventEmitter#68]
First off, great work on this lib.  It's a great implementation that I'm using in my production app.

Just wanted to mention an idea I just had, that of more easily extending existing objects to support event registration.

In your guide, you recommend how to [extend](https://github.com/Wolfy87/EventEmitter/blob/master/docs/guide.md#extending-with-the-eventemitter-class) a user object to have the EventEmitter methods so that calling code can register for events.  I even looked at the Heir script you wrote to assist this.  

However, it seems to me to be very common functionality to include events as part of a Javascript class thus I believe that it should be very simple process and part of this library.  Thus I don't want to have to load in another lib just to "extend" my class with the proper methods.

Furthermore, I want only the "client" methods exposed (only the methods for de/registration of events).  The emit (and related) methods should not be added for exposure since they should be used inside the class lib and not be visible outside the class.

For a very similar example, see [JQuery's Deferred Object](http://api.jquery.com/category/deferred-object/) which exposes a [.promise()](http://api.jquery.com/deferred.promise/) method that returns an object appropriate for client consumption which contains only the partial subset of methods for registering for events (but not any that resolve the Deferred object)

Thus I propose a method addition that mixes in EventEmitter methods to a given object but only those methods safe for clients.

So something like:

```
MyClass = function() {
   this.ee = new EventEmitter();

   ee.extendObject(this);  // adds registration methods to this or this's prototype
}

MyClass.prototype.bar = function() {
   this.ee.trigger('someEvent');   // valid inside the class with direct access to ee
}

var foo = new MyClass();
foo.on('someEvent', function() { ... });   // register for an event
foo.emit(); // throws invalid method

foo.ee.trigger(); // in theory possible but discouraged since ee is supposed to be private

```

Thoughts?

**Comment by cjsauer** [comment]
I'm still interested in this problem and am wondering how it would be handled with the new ES6 facilities, mainly:

```js
class Person extends EventEmitter {}
```

The above doesn't seem to work, and using your Heir package also doesn't seem to play nice with ES6 classes. Has anyone tried using this package in a strictly ES6 project?

**Comment by cjsauer** [comment]
Update: my above example *does* work, I just wasn't calling `super()` in the constructor of Person. Carry on everyone! :sweat_smile:
