### ISSUE TITLE
Would anyone mind if I swapped to the unlicense?

### ISSUE THREAD

**Issue by Olical** [Olical/EventEmitter#84]
This is a general question to anyone that uses this script in an environment where a license change could cause a lot of screaming (i.e. financial institutions).

All of my new projects are (un)licensed under [the unlicense](http://unlicense.org/) which relinquishes my right to basically everything, but essentially removes all barriers for usage and modification. If you want to take my script, modify it and put it in a paid product without telling anyone, do it. I don't care and you'll be able to do it regardless of the magical three character strings I place in the first comment and `README.md` anyway. I don't care, I can't stop you either way. We're software engineers, go build stuff and stop worrying about legalities.

So, yeah. I'm swapping my repositories over to this one by one but this happens to be my most popular thing by far, I thought I should ask first. Thoughts?

**Comment by ebeeson** [comment]
I sympathize with what you're trying to accomplish, but it seems like MIT or CC0 (or probably even Apache) licenses are better at meeting your needs than Unlicense:

http://programmers.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense

http://programmers.stackexchange.com/questions/182137/whats-the-difference-between-wtfpl-cc0-and-public-domain

https://github.com/docopt/docopt.rs/issues/1

What you've done isn't an issue for me, so it doesn't really matter. It's just that, as a fellow shepherd of open source software, I'm curious what inspired you to do this as it doesn't actually seem congruent with your intentions.

**Comment by Olical** [comment]
The only thing I need is a licence I can drop in which tells users they can do whatever they want. I wrote some code to solve a problem, it's on the internet now, go wild. I don't mind which one it is, I don't really care as long as it doesn't restrict anyone from doing anything.

Licenses don't protect me or give me anything (in my opinion). If someone wants to take my code and attempt to sell it or claim it as their own, be my guest. A text file next to the source won't stop them, I'm not fighting legal battles over a chunk of JavaScript.

Basically: I don't want to worry about legal crap or attribution and copyright, I just want it out of the way so I can publish my code knowing I'm not asking anyone to do anything extra just to solve a problem.

That other thread turned into a pretty messy argument over something pretty small, I hope that doesn't happen here D: I  apologise if any of my opinions seem completely wrong or stupid, that's just how I feel after working on little open source things for the past five years or so.

I hope this quick little ramble has explained my reasoning though! :)

**Comment by SCLeoX** [comment]
@Olical, I admire you for your decision. To be honest, I cannot do it with my projects, but you did. :+1:
