### ISSUE TITLE
EventEmitter Not Found

### ISSUE THREAD

**Issue by coreybutler** [Olical/EventEmitter#97]
Using the latest code with just a `console.log(EventEmitter)` yields an error (EventEmitter is undefined). I reverted to version 4.1.0 (because it was on the jsfiddle example) which ran smoothly. Seems like the latest version isn't working though.

**Comment by Wolfy87** [comment]
How are you loading the script, can you share your example?

**Comment by coreybutler** [comment]
I downloaded `EventEmitter.min.js` from the master branch and load it as follows:

```html
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Test Page</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">
  <script src="lib/svg.js"></script>
  <script src="lib/EventEmitter.min.js"></script>
  <script src="http://localhost:12346/livereload.js"></script>
</head>
<body>
  Test
  <script>
    console.log(EventEmitter);     // <--- Problem
    var bus = new EventEmitter();
    console.log(bus);
  </script>
</body>
```

The console just states `EventEmitter is not defined.`

However; when I replace the EventEmitter code using the older code from http://jsfiddle.net/Wolfy87/qXQu9/, the above code works without a problem.

**Comment by Wolfy87** [comment]
Hm, are you sure the script has loaded by that point? It should block until done, but I'd just confirm that. This works fine for me: https://jsfiddle.net/pje48erg/

**Comment by coreybutler** [comment]
The fiddle initially failed on my system due to explicit mime type checking, but I modified it slightly (using rawgit.com instead of github), which worked.

I'm using this within an [Electron app](http://electron.atom.io), which still fails even after the modification, despite assuring the DOM/script is fully loaded before logging the `EventEmitter`. It seems like an environment issue, not necessarily your library. I still don't see how the 4.1.0 version works while the latest doesn't, but I haven't looked at the diff in depth yet.

Since Electron can leverage node's EventEmitter, my project doesn't _necessitate_ the use of your EventEmitter, but my goal was to reuse the code in a browser version of the app. I realize this is an edge case. If you're interested in getting this to work within Electron, I'm happy to keep troubleshooting. Otherwise, I'm just as content closing this issue.

Thanks for your help and the time you put into this code base.

**Comment by coreybutler** [comment]
I came across this issue with other libraries too. I'll spare the deep details. Electron was allocating the `EventEmitter` to `modules.export` as opposed to the global/window.

If anyone else is doing some mad science with this library and Electron as I have been, the simple-yet-not-immediately-obvious fix is to add the following immediately after including the EventEmitter.

```js
EventEmitter = module.exports;
```
